### ISSUE TITLE
Shuffle/Randomize

### ISSUE THREAD

**Issue by Kaichewz** [sameerdash2/comment-viewer#7]
In the "sort by" area maybe add a Randomize or Shuffle Comments button

**Comment by sameerdash2** [comment]
Randomizing comments is possible, but it'll be hard to offer pagination ("show more") without showing duplicate comments. Any method to do this in SQLite seems overly convoluted (https://stackoverflow.com/a/75089040).

An alternative is to have a button that just picks 1 random comment at a time (or 5, 10, etc) but that'd need a lot of UI changes and other sites can do this already. So I think it's not worth the effort. Thanks for the suggestion though!
